plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.graalvm.buildtools.native' version '0.10.6'
}

group = 'com.abrxu'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

task buildIndex(type: JavaExec) {
	dependsOn compileJava, processResources
	classpath = sourceSets.main.compileClasspath + sourceSets.main.output.classesDirs
	mainClass = 'com.abrxu.fraud_detection_rinha.IndexBuilder'
	args = [
		'build/resources/main/references.json.gz',
		'build/resources/main/index.bin'
	]
	jvmArgs = ['-Xmx512m']
}

classes.dependsOn buildIndex

bootJar {
	exclude 'references.json.gz'
}

graalvmNative {
	binaries {
		main {
			buildArgs.add('-O3')
			buildArgs.add('--enable-url-protocols=http')
			buildArgs.add('--report-unsupported-elements-at-runtime')
		}
	}
}
